In [1]:
import pandas as pd
import numpy as np

In [4]:
phosphosite_df = pd.read_csv("../dataset/phosphosite_org/ptmsite.csv", sep="")
phosphosite_df

                                                                                                                                                                                                                                                                                                                                                 041923
PhosphoSitePlus(R) (PSP) was created by Cell Si...  the following acknowledgements must be include...  www.phosphosite.org" must be included at appro...  and (b) the following citation must be include...  Zhang B  Murray B  Kornhauser JM  Latham V  Skrzypek E PhosphoSitePlus  2014: mutations   PTMs and recalibrations. Nucleic Acids Res. 2...
GENE\tPROTEIN\tACC_ID\tHU_CHR_LOC\tMOD_RSD\tSIT... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
0610009B22Rik\t0610009B22Rik\tQ8R3W2\t11|11 B1.... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
1110035H17Rik\t1110035H17Rik\tQ9CTA4\t7|7\tS10-... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
1110035H17Rik\t1110035H17Rik\tQ9CTA4\t7|7\tT11-... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
...                                                                                                                                                                                                                                                                                                                                                 ...
ZZZ3\tZZZ3\tQ8IYH5\t1p31.1\tS606-p\t23077718\th... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
Zzz3\tZZZ3\tQ6KAQ7\t3|3 H3\tS613-p\t23077718\tm... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
ZZZ3\tZZZ3\tQ8IYH5\t1p31.1\tY670-p\t23077724\th... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
ZZZ3\tZZZ3\tQ8IYH5\t1p31.1\tS677-p\t23077721\th... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN
ZZZ3\tZZZ3\tQ8IYH5\t1p31.1\tS777-p\t41455930\th... NaN                                                NaN                                                NaN                                                NaN      NaN       NaN            NaN       NaN                         NaN                                                             NaN

[378741 rows x 1 columns]

In [2]:
dataframe_plm = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/phosphoELM_all_2015-04.csv", sep="\t")
dataframe_plm

,acc,sequence,position,code,pmids,kinases,source,species,entry_date
0,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,17114649,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
1,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,17242355,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
2,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,15345747,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
3,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,296,S,17114649,NaN,HTP,Mus musculus,2007-07-13 15:17:45.666219+02
4,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,296,S,17242355,NaN,HTP,Mus musculus,2007-07-13 15:17:45.666219+02
...,...,...,...,...,...,...,...,...,...
57385,Q9NNX1,MNGTRNWCTLVDVHPEDQAAGSVDILRLTLQGELTGDELEHIAQKA...,378,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:22.267702+01
57386,P33552,MAHKQIYYSDKYFDEHYEYRHVMLPRELSKQVPKTHLMSEEEWRRL...,51,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:26.8579+01
57387,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,695,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.603887+01
57388,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,291,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.492959+01
57389,Q9UGJ1,MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLC...,441,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:30.010184+01

In [3]:
humans = dataframe_plm[dataframe_plm["species"] == "Homo sapiens"]
#df2['id'].isin(['SP.POP.TOTL','NY.GNP.PCAP.CD'])
humans

,acc,sequence,position,code,pmids,kinases,source,species,entry_date
14,O14543,MVTHSKFPAAGMSRPLDTSLRLKTFSSKSEYQLVVNAVRKLQESGF...,204,Y,12783885,Lck,LTP,Homo sapiens,2006-10-17 12:06:48.16767+02
15,O14543,MVTHSKFPAAGMSRPLDTSLRLKTFSSKSEYQLVVNAVRKLQESGF...,221,Y,12783885,NaN,LTP,Homo sapiens,2006-10-17 12:06:48.271076+02
16,O14543,MVTHSKFPAAGMSRPLDTSLRLKTFSSKSEYQLVVNAVRKLQESGF...,221,Y,15173187,Lck,LTP,Homo sapiens,2006-10-17 12:06:48.271076+02
17,O14746,MPRAPRCRAVRSLLRSHYREVLPLATFVRRLGPQGWRLVQRGDPAA...,797,S,16565220,NaN,HTP,Homo sapiens,2006-10-17 11:57:53.909276+02
18,O14746,MPRAPRCRAVRSLLRSHYREVLPLATFVRRLGPQGWRLVQRGDPAA...,824,S,10224060,PKB_group,LTP,Homo sapiens,2004-12-31 00:00:00+01
...,...,...,...,...,...,...,...,...,...
57385,Q9NNX1,MNGTRNWCTLVDVHPEDQAAGSVDILRLTLQGELTGDELEHIAQKA...,378,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:22.267702+01
57386,P33552,MAHKQIYYSDKYFDEHYEYRHVMLPRELSKQVPKTHLMSEEEWRRL...,51,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:26.8579+01
57387,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,695,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.603887+01
57388,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,291,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.492959+01
57389,Q9UGJ1,MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLC...,441,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:30.010184+01

In [4]:
target_seq_len = 33
target_left_right = 16

In [5]:
def write_fasta(dataframe, file_path):
    dataframe = dataframe.drop_duplicates(subset=['sequence'])
    print("After duplicates removal")
    print(dataframe)
    data_fasta = ""
    for i, row in dataframe.iterrows():
        data_fasta += ">" + row["acc"] + "\n"
        data_fasta += row["sequence"] + "\n"
    
    with open(file_path, 'w') as f:
        f.write(data_fasta)
    return dataframe


r_S_id = list()
r_S_seq = list()
r_T_id = list()
r_T_seq = list()

for i, row in humans.iterrows():
    pos = int(row["position"])
    if pos > 33 and pos + target_left_right < len(row["sequence"]):
        extracted_seq = row["sequence"][pos - target_left_right - 1: pos + target_left_right]
        if row["code"] == "S":
            r_S_id.append(row["acc"])
            r_S_seq.append(extracted_seq)
        if row["code"] == "T":
            r_T_id.append(row["acc"])
            r_T_seq.append(extracted_seq)
        
            
S_dataframe = pd.DataFrame(zip(r_S_id, r_S_seq), columns=["acc", "sequence"])
T_dataframe = pd.DataFrame(zip(r_T_id, r_T_seq), columns=["acc", "sequence"])

print(S_dataframe)
print()
print(T_dataframe)

          acc                           sequence
0      O14746  QETSPLRDAVVIEQSSSLNEASSGLFDVFLRFM
1      O14746  VFLRFMCHHAVRIRGKSYVQCQGIPQGSILSTL
2      O14746  GVPLGLPAPGARRRGGSASRSLPLPKRPRRGAA
3      O14867  QTPQCKLRRYQGNAKASPPLQDSASQTYESMCL
4      O14867  SQKRSECPWLGIRISESPEPGQRTFTTLSSVNC
...       ...                                ...
24423  Q8NFH3  ENYISLWSIGDFGNLDSDGGFEGDHQLLCDIRH
24424  P33552  THLMSEEEWRRLGVQQSLGWVHYMIHEPEPHIL
24425  Q96SB8  ENTRPKFLSRDVDSEISDLENEVENKTAQILNL
24426  Q96SB8  RQCVEKEERFQSIAGLSTMKTNLESLKHEMAWA
24427  Q9UGJ1  HKADATQAREGPSRETSPREAPASGWAALGLSY

[24428 rows x 2 columns]

           acc                           sequence
0       O14746  RTAQTQLSRKLPGTTLTALEAAANPALPSDFKT
1       O15117  VNQDHDLKPLGPKSGPTPPTSENEQKQAFPKLT
2       O15143  RERFQNLDKKASSEGGTAAGAGLDSLHKNSVSQ
3       O15350  STMDQMSSRAASASPYTPEHAASVPTHSPYAQP
4       O15392  FLKLDRERAKNKIAKETNNKKKEFEETAKKVRR
...        ...                                ...
5657  P33981-1  KTPSSNTLDDYMSCFRTPVVKNDFPPACQLSTP
5658  P33981-1  QMQPDTTSVVKDSQVGTVNYMPPEAIKDMSSSR
5659  P33981-1  QMQPDTTSVVKDSQVGTVNYMPPEAIKDMSSSR
5660  Q9Y4B5-4  RPANRRPPSRWAPHSPTASQPQSPGDPTSLEEH
5661    P50748  HIKAHEVAQAKHKPGSTPEPIAAEVRSPSMESK

[5662 rows x 2 columns]

In [6]:
dedup_S_dataframe = write_fasta(S_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_S.fasta")  
dedup_S_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_S.tsv", sep="\t", index=None)

After duplicates removal
          acc                           sequence
0      O14746  QETSPLRDAVVIEQSSSLNEASSGLFDVFLRFM
1      O14746  VFLRFMCHHAVRIRGKSYVQCQGIPQGSILSTL
2      O14746  GVPLGLPAPGARRRGGSASRSLPLPKRPRRGAA
3      O14867  QTPQCKLRRYQGNAKASPPLQDSASQTYESMCL
4      O14867  SQKRSECPWLGIRISESPEPGQRTFTTLSSVNC
...       ...                                ...
24423  Q8NFH3  ENYISLWSIGDFGNLDSDGGFEGDHQLLCDIRH
24424  P33552  THLMSEEEWRRLGVQQSLGWVHYMIHEPEPHIL
24425  Q96SB8  ENTRPKFLSRDVDSEISDLENEVENKTAQILNL
24426  Q96SB8  RQCVEKEERFQSIAGLSTMKTNLESLKHEMAWA
24427  Q9UGJ1  HKADATQAREGPSRETSPREAPASGWAALGLSY

[16833 rows x 2 columns]

In [7]:
dedup_T_dataframe = write_fasta(T_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_T.fasta")  
dedup_T_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_T.tsv", sep="\t", index=None)

After duplicates removal
           acc                           sequence
0       O14746  RTAQTQLSRKLPGTTLTALEAAANPALPSDFKT
1       O15117  VNQDHDLKPLGPKSGPTPPTSENEQKQAFPKLT
2       O15143  RERFQNLDKKASSEGGTAAGAGLDSLHKNSVSQ
3       O15350  STMDQMSSRAASASPYTPEHAASVPTHSPYAQP
4       O15392  FLKLDRERAKNKIAKETNNKKKEFEETAKKVRR
...        ...                                ...
5653  P33981-1  LKLIDFGIANQMQPDTTSVVKDSQVGTVNYMPP
5657  P33981-1  KTPSSNTLDDYMSCFRTPVVKNDFPPACQLSTP
5658  P33981-1  QMQPDTTSVVKDSQVGTVNYMPPEAIKDMSSSR
5660  Q9Y4B5-4  RPANRRPPSRWAPHSPTASQPQSPGDPTSLEEH
5661    P50748  HIKAHEVAQAKHKPGSTPEPIAAEVRSPSMESK

[4276 rows x 2 columns]

In [8]:
# create negative dataset
S_neg_id = list()
S_neg_seq = list()

T_neg_id = list()
T_neg_seq = list()

def extract_neg_seq(original_seq, s_id, pos, s_len=33):
    r_id = list()
    r_seq = list()
    for p in pos:
        if p > s_len:
            extracted_seq = original_seq[p - target_left_right: p + target_left_right + 1]
            if len(extracted_seq) >= s_len:
                r_id.append(s_id)
                r_seq.append(extracted_seq)
    return r_id, r_seq
                        

for i, row in humans.iterrows():
    if len(row["sequence"]) > 33:

        S_pos = [pos for pos, char in enumerate(row["sequence"]) if char == "S"]
        T_pos = [pos for pos, char in enumerate(row["sequence"]) if char == "T"]
        
        if row["code"] == "S":
            # exclude POS position
            S_pos = [ item for item in S_pos if item != row["position"] - 1 ]
            ids, seqs = extract_neg_seq(row["sequence"], row["acc"], S_pos)
            S_neg_id.extend(ids)
            S_neg_seq.extend(seqs)
        if row["code"] == "T":
            # exclude POS position
            T_pos = [ item for item in T_pos if item != row["position"] - 1 ]
            ids, seqs = extract_neg_seq(row["sequence"], row["acc"], T_pos)
            T_neg_id.extend(ids)
            T_neg_seq.extend(seqs)


S_neg_dataframe = pd.DataFrame(zip(S_neg_id, S_neg_seq), columns=["acc", "sequence"])
T_neg_dataframe = pd.DataFrame(zip(T_neg_id, T_neg_seq), columns=["acc", "sequence"])

In [9]:
S_neg_dataframe

            acc                           sequence
0        O14746  CLVCVPWDARPPPAAPSFRQVSCLKELVARVLQ
1        O14746  PWDARPPPAAPSFRQVSCLKELVARVLQRLCER
2        O14746  ALLDGARGGPPEAFTTSVRSYLPNTVTDALRGS
3        O14746  DGARGGPPEAFTTSVRSYLPNTVTDALRGSGAW
4        O14746  SVRSYLPNTVTDALRGSGAWGLLLRRVGDDVLV
...         ...                                ...
2844573  Q9UGJ1  RGAAQLSILVKGFSRQSSLLFKILSSVRNHQIN
2844574  Q9UGJ1  GAAQLSILVKGFSRQSSLLFKILSSVRNHQINS
2844575  Q9UGJ1  LVKGFSRQSSLLFKILSSVRNHQINSDLAQLLL
2844576  Q9UGJ1  VKGFSRQSSLLFKILSSVRNHQINSDLAQLLLR
2844577  Q9UGJ1  SLLFKILSSVRNHQINSDLAQLLLRLDYNKYYT

[2844578 rows x 2 columns]

In [10]:
T_neg_dataframe

           acc                           sequence
0       O14746  GFALLDGARGGPPEAFTTSVRSYLPNTVTDALR
1       O14746  FALLDGARGGPPEAFTTSVRSYLPNTVTDALRG
2       O14746  GPPEAFTTSVRSYLPNTVTDALRGSGAWGLLLR
3       O14746  PEAFTTSVRSYLPNTVTDALRGSGAWGLLLRRV
4       O14746  CAYQVCGPPLYQLGAATQARPPPHASGPRRRLG
...        ...                                ...
355922  P50748  SCDPQVILKQLEEHMNTGQLAGFSHQIRSLILN
355923  P50748  ILNNIINKKEFGILAKTKYFQMLKMHAMNTNNI
355924  P50748  LAKTKYFQMLKMHAMNTNNITELVNYLANDLSL
355925  P50748  KYFQMLKMHAMNTNNITELVNYLANDLSLDEAS
355926  P50748  NYLANDLSLDEASVLITEYSKHCGKPVPPDTAP

[355927 rows x 2 columns]

In [11]:
dedup_S_neg_dataframe = write_fasta(S_neg_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_S.fasta")  
dedup_S_neg_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_S.tsv", sep="\t", index=None)

After duplicates removal
            acc                           sequence
0        O14746  CLVCVPWDARPPPAAPSFRQVSCLKELVARVLQ
1        O14746  PWDARPPPAAPSFRQVSCLKELVARVLQRLCER
2        O14746  ALLDGARGGPPEAFTTSVRSYLPNTVTDALRGS
3        O14746  DGARGGPPEAFTTSVRSYLPNTVTDALRGSGAW
4        O14746  SVRSYLPNTVTDALRGSGAWGLLLRRVGDDVLV
...         ...                                ...
2844573  Q9UGJ1  RGAAQLSILVKGFSRQSSLLFKILSSVRNHQIN
2844574  Q9UGJ1  GAAQLSILVKGFSRQSSLLFKILSSVRNHQINS
2844575  Q9UGJ1  LVKGFSRQSSLLFKILSSVRNHQINSDLAQLLL
2844576  Q9UGJ1  VKGFSRQSSLLFKILSSVRNHQINSDLAQLLLR
2844577  Q9UGJ1  SLLFKILSSVRNHQINSDLAQLLLRLDYNKYYT

[286507 rows x 2 columns]

In [12]:
dedup_T_neg_dataframe = write_fasta(T_neg_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_T.fasta")  
dedup_T_neg_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_T.tsv", sep="\t", index=None)

After duplicates removal
           acc                           sequence
0       O14746  GFALLDGARGGPPEAFTTSVRSYLPNTVTDALR
1       O14746  FALLDGARGGPPEAFTTSVRSYLPNTVTDALRG
2       O14746  GPPEAFTTSVRSYLPNTVTDALRGSGAWGLLLR
3       O14746  PEAFTTSVRSYLPNTVTDALRGSGAWGLLLRRV
4       O14746  CAYQVCGPPLYQLGAATQARPPPHASGPRRRLG
...        ...                                ...
355922  P50748  SCDPQVILKQLEEHMNTGQLAGFSHQIRSLILN
355923  P50748  ILNNIINKKEFGILAKTKYFQMLKMHAMNTNNI
355924  P50748  LAKTKYFQMLKMHAMNTNNITELVNYLANDLSL
355925  P50748  KYFQMLKMHAMNTNNITELVNYLANDLSLDEAS
355926  P50748  NYLANDLSLDEASVLITEYSKHCGKPVPPDTAP

[98375 rows x 2 columns]

In [13]:
from sklearn.model_selection import train_test_split


all_neg_S = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_S.tsv", sep="\t")

all_neg_S = all_neg_S.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_neg_S.index))

test_neg_S = all_neg_S[split_size:]
train_neg_S = all_neg_S[:split_size]

train_neg_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_S.tsv", sep="\t", index=None)
test_neg_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_S.tsv", sep="\t", index=None)

In [14]:
all_pos_S = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_S.tsv", sep="\t")

all_pos_S = all_pos_S.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_pos_S.index))
test_pos_S = all_pos_S[split_size:]
train_pos_S = all_pos_S[:split_size]

train_pos_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_S.tsv", sep="\t", index=None)
test_pos_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_S.tsv", sep="\t", index=None)

In [15]:
all_neg_T = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_T.tsv", sep="\t")

all_neg_T = all_neg_T.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_neg_T.index))

test_neg_T = all_neg_T[split_size:]
train_neg_T = all_neg_T[:split_size]

train_neg_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_T.tsv", sep="\t", index=None)
test_neg_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_T.tsv", sep="\t", index=None)

In [16]:
all_pos_T = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_T.tsv", sep="\t")

all_pos_T = all_pos_T.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_pos_T.index))
train_pos_T = all_pos_T[:split_size]
test_pos_T = all_pos_T[split_size:]

train_pos_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_T.tsv", sep="\t", index=None)
test_pos_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_T.tsv", sep="\t", index=None)

In [17]:
def write_tsv_fasta(file_path, save_to_file, max_rows=20000):
    fasta_text = ""
    dataframe = pd.read_csv(file_path, sep="\t")
    print(dataframe)
    for i, row in dataframe.iterrows():
        fasta_text += ">" + row[0] + "\n"
        fasta_text += row[1] + "\n"
        if i > max_rows:
            break
    with open(save_to_file, "w") as f:
        f.write(fasta_text)

In [18]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_S.fasta")

          acc                           sequence
0      Q92794  QDGWDGKQENEERLFGSQEIMTEKDMELFRDIQ
1      Q15942  PAPKFSPVTPKFTPVASKFSPGAPGGSGSQPNQ
2      Q9HC52  QLARRQDSDLVQCGVTSPSSAEATGKLAVDTFP
3      Q9NYV4  SRSPHRKWSDSSKQDDSPSGASYGQDYDLSPSR
4      A6ND36  VAKKLVNPKYALVKAKSVDEIAKISSEKQEAKK
...       ...                                ...
13461  P51825  PLISLPSPVPPLSPIHSNQQTLPRTQGSSKVHG
13462  O43164  EEYDGEHDCMFLDPPYSRVITQRETENNQMTSE
13463  Q9UPY3  LTPRHLNQKGKALPLSSAEKRKAKWESLQNKQI
13464  Q8WTQ7  RKPSDCDSKELQRRRRSLALPGLQGCAELRQKL
13465  Q15906  EEDEFYQTTYGGFTEESGDDEYQGDQSDTEDEV

[13466 rows x 2 columns]

In [19]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_T.fasta")

                  acc                           sequence
0              Q9H6F5  SRTRRALVEFESNPEETREPGSPPSVQRAGLGS
1              P49815  QPSQPLSKSSSSPELQTLQDILGDPGDKADVGR
2              P51826  RSGETNSCVEEIIREMTWLPPLSAIQAPGKVEP
3              O75533  ERDTPGHGSGWAETPRTDRGGDSIGETPTPGAS
4              Q9H0K1  ADFGFGNFFKSGELLATWCGSPPYAAPEVFEGQ
...               ...                                ...
3415           Q9Y4E1  GEAKPRKTLKEKKERRTPSDDEEDNLFAPPKLT
3416           P18887  TKPTQAAGPSSPQKPPTPEETKAASPVLQEDID
3417           Q15003  SPYPCHPPKTAQQNGDTPEAQGLDITTYGESNL
3418  ENSP00000313171  PFDSESPIRMKFTRISTPKKSKKKSNKRSEKSE
3419         Q9H0E9-2  QTPNTVAASPAASGAPTLSRLLEAGPTQFTTPL

[3420 rows x 2 columns]

In [20]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_S.fasta", len(train_pos_S.index))

           acc                           sequence
0       Q7L804  RASNIMPSSSFHMSPTSNEDLRKIPDSNPFDAT
1       Q9UER7  HPEVVPFLYNRQQRAHSLFLASAEFCNILSRVL
2       O94806  GSKYYKEIPLSEILRISSPRDFTNISQGSNPHC
3       Q9NZV8  RPSSHSPSLSSQQGVTSTCCSRRHKKTFRIPNA
4       Q8WXG6  GNRAQKLLRPNSLRLASDSDAESDSRASSPNST
...        ...                                ...
229200  Q03468  DQFGYWKRSGKMIVVESLLKIWHKQGQRVLLFS
229201  Q99569  YVISTGVSPSRGSLRTSLGSGFGSPSVTDPRPL
229202  Q15027  QADSERLLQLWVSAVQSSIASAFSQARLDDSPR
229203  Q9BX63  GKNGKSCYFYHGVHKISDQHTLQTFQGMCKAWD
229204  Q6AHZ1  TLKKTSKNNYQIVKTTSENILKAKFNCWFCGRV

[229205 rows x 2 columns]

In [21]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_T.fasta", len(train_pos_T.index))

          acc                           sequence
0      Q8NEM2  HVVSSTMMAGLLRSLLTDRLCQEPGEEEREIQF
1      P20020  RQPSIASQHHDVTNISTPTHIRVVNAFRSSLYE
2      Q96R06  ENLKDTVENLTAKLASTIADNQEQDLEKTRQYS
3      O43830  CGKTFTVNQLLTLHHRTHSGEKPYQCSECGKTF
4      P78536  LVHRVKRRADPDPMKNTCKLLVVADHRFYRYMG
...       ...                                ...
78695  Q99700  HVPQAHVQSGMVPSHPTAHAPMMLMTTQPPGGP
78696  O60271  VLIIDAVQPGNILDSFTVCNSHVLCIASVPGAR
78697  Q5T4S7  NTKPGGFTIEISNNNSTMVMTGMRIQIGTQAIE
78698  Q8WYB5  CGSSGHPSCLKFCPELTTNVKALRWQCIECKTC
78699  O94844  ASVQPGPFRTLLQFLYTGQLDEKEKDLVGLAQI

[78700 rows x 2 columns]

In [22]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_S.fasta")

           acc                           sequence
0     Q9Y4B5-4  ANRRPPSRWAPHSPTASQPQSPGDPTSLEEHGG
1       Q13428  TPSRTETLVEETAAESSEDDVVAPSQSLLSGYM
2       Q32MZ4  SLGGTSSRRGSGDTSISIDTEASIREIKELNEL
3       O95817  SSVQGASSREGSPARSSTPLHSPSPIRVHTVVD
4       P29317  RAPDSLKTLADFDPRVSIRLPSTSGSEGVPFRT
...        ...                                ...
3362    Q12879  SCLSNMPTYSGHFTMRSPFKCDACLRMGNLYDI
3363    O00444  LSVSKRSGGGENEERYSPTDNNANIFNFFKEKT
3364    Q6NUK4  AAVKSQGAITERLRSFSMHDLTTIQGDEPVGQR
3365    P50552  QKRQQPGPSEHIERRVSNAGGPPAPPAGGPPPP
3366    P35125  SKPRILAREVKKVDAQSSAGKEDMLLSKSPSSL

[3367 rows x 2 columns]

In [23]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_T.fasta")

        acc                           sequence
0    Q16594  LGTPTPQTMSVSTKVGTPMSLTGQRFTVQMPTS
1    Q9P2D1  VNRRQMFDFQGLIPGYTPTTVDSPLQKRSFAEL
2    P46013  KAQALEELTGFRELFQTPCTDNPTTDEKTTKKI
3    O95487  SSTRTPPTANHPVEPVTSVTQPSELLQQKGVQY
4    Q8IY81  ISLSSGEEDEGDEEDSTAGTTKQPSKEEEEEEE
..      ...                                ...
851  Q06830  IGASVDSHFCHLAWVNTPKKQGGLGPMNIPLVS
852  O43933  GVPGKDQLFSQPPVLRTASQEGCQELTQEQRDQ
853  Q03164  TDSPGPSQISNAAVQTTPPHLKPATEKLIVVNQ
854  Q9Y6I3  LAEAVGSPPPAATPTPTPPTRKTPESFLGPNAA
855  Q13523  TLRRRSQEKIGKARSPTDDKVKIEDKSKSKDRK

[856 rows x 2 columns]

In [24]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_S.fasta", len(test_pos_S.index))

                   acc                           sequence
0               P41181  ERRGENPGTPALSIGFSVALGHLLGIHYTGCSM
1               P18505  STLEIRNETSGSEVLTSVSDPKATMYSYDSASI
2               Q8N5A5  DSAQSSALCPSLAVVGSDAVDSGTCSSAFAGWE
3      ENSP00000374586  KLTNNTLDQEGHIILHSMHRYLPRLHLVPAEKA
4               Q00059  PRWFSSVLASCPKKPVSSYLRFSKEQLPIFKAQ
...                ...                                ...
57297           O14874  RISPLFGHLDMHSGAQSGPMHGFGFGLPTSRAY
57298           Q8N4S0  RSSGRDFEDSEKESCPSSDEVDEEEEEDNYESD
57299           O60239  RGLSSSSGSGGSSKSQSSTSPEGQALENRMKQL
57300           P32942  RILCSVYCNGSQITGSSNITVYGLPERVELAPL
57301           Q9Y2W1  GYGNYRSNWQNYRQAYSPRRGRSRSRSPKRRSP

[57302 rows x 2 columns]

In [25]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_T.fasta", len(test_pos_T.index))

          acc                           sequence
0      P30307  GEITATQLTTSADLDETGHLDSSGLQEVHLAGM
1      Q63ZY3  ATPTGLGSLTPSAAGSTASLVGVGLPPPTPRSS
2      Q7Z6Z7  PQVNQQQLQQLMDMGFTREHAMEALLNTSTMEQ
3      Q9UI47  ACLEHSDVASLKASKDTVCEEIQNALNVISNAS
4      O60486  ELLDIDSSSVILEDGITKLNTIGHYEISNGSTI
...       ...                                ...
19670  Q14527  GLRRLQSLIKNITLRRTKTSKIKGKPVLELPER
19671  P38398  QTERSVESSSISLVPGTDYGTQESISLLEVSTL
19672  P35568  GKPGSFRVRASSDGEGTMSRPASVDGSPVSPST
19673  P50851  STASFVLAWLLRIEPFTTYFLNLQGGKFDHADR
19674  Q03188  SVRNELPMHHNSSRKSTKKTNQSSKNIRKKTIP

[19675 rows x 2 columns]