In [8]:
import pandas as pd
import numpy as np

In [10]:
phosphosite_df = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/phosphoELM_all_2015-04.csv", sep="\t")
phosphosite_df

,acc,sequence,position,code,pmids,kinases,source,species,entry_date
0,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,17114649,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
1,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,17242355,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
2,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,15345747,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
3,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,296,S,17114649,NaN,HTP,Mus musculus,2007-07-13 15:17:45.666219+02
4,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,296,S,17242355,NaN,HTP,Mus musculus,2007-07-13 15:17:45.666219+02
...,...,...,...,...,...,...,...,...,...
57385,Q9NNX1,MNGTRNWCTLVDVHPEDQAAGSVDILRLTLQGELTGDELEHIAQKA...,378,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:22.267702+01
57386,P33552,MAHKQIYYSDKYFDEHYEYRHVMLPRELSKQVPKTHLMSEEEWRRL...,51,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:26.8579+01
57387,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,695,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.603887+01
57388,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,291,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.492959+01
57389,Q9UGJ1,MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLC...,441,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:30.010184+01

In [11]:
dataframe_plm = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/phosphoELM_all_2015-04.csv", sep="\t")
dataframe_plm

,acc,sequence,position,code,pmids,kinases,source,species,entry_date
0,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,17114649,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
1,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,17242355,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
2,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,304,S,15345747,NaN,HTP,Mus musculus,2005-03-14 12:16:11.108314+01
3,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,296,S,17114649,NaN,HTP,Mus musculus,2007-07-13 15:17:45.666219+02
4,O08539,MAEMGSKGVTAGKIASNVQKKLTRAQEKVLQKLGKADETKDEQFEQ...,296,S,17242355,NaN,HTP,Mus musculus,2007-07-13 15:17:45.666219+02
...,...,...,...,...,...,...,...,...,...
57385,Q9NNX1,MNGTRNWCTLVDVHPEDQAAGSVDILRLTLQGELTGDELEHIAQKA...,378,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:22.267702+01
57386,P33552,MAHKQIYYSDKYFDEHYEYRHVMLPRELSKQVPKTHLMSEEEWRRL...,51,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:26.8579+01
57387,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,695,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.603887+01
57388,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,291,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.492959+01
57389,Q9UGJ1,MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLC...,441,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:30.010184+01

In [12]:
humans = dataframe_plm[dataframe_plm["species"] == "Homo sapiens"]
#df2['id'].isin(['SP.POP.TOTL','NY.GNP.PCAP.CD'])
humans

,acc,sequence,position,code,pmids,kinases,source,species,entry_date
14,O14543,MVTHSKFPAAGMSRPLDTSLRLKTFSSKSEYQLVVNAVRKLQESGF...,204,Y,12783885,Lck,LTP,Homo sapiens,2006-10-17 12:06:48.16767+02
15,O14543,MVTHSKFPAAGMSRPLDTSLRLKTFSSKSEYQLVVNAVRKLQESGF...,221,Y,12783885,NaN,LTP,Homo sapiens,2006-10-17 12:06:48.271076+02
16,O14543,MVTHSKFPAAGMSRPLDTSLRLKTFSSKSEYQLVVNAVRKLQESGF...,221,Y,15173187,Lck,LTP,Homo sapiens,2006-10-17 12:06:48.271076+02
17,O14746,MPRAPRCRAVRSLLRSHYREVLPLATFVRRLGPQGWRLVQRGDPAA...,797,S,16565220,NaN,HTP,Homo sapiens,2006-10-17 11:57:53.909276+02
18,O14746,MPRAPRCRAVRSLLRSHYREVLPLATFVRRLGPQGWRLVQRGDPAA...,824,S,10224060,PKB_group,LTP,Homo sapiens,2004-12-31 00:00:00+01
...,...,...,...,...,...,...,...,...,...
57385,Q9NNX1,MNGTRNWCTLVDVHPEDQAAGSVDILRLTLQGELTGDELEHIAQKA...,378,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:22.267702+01
57386,P33552,MAHKQIYYSDKYFDEHYEYRHVMLPRELSKQVPKTHLMSEEEWRRL...,51,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:26.8579+01
57387,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,695,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.603887+01
57388,Q96SB8,MAKRKEENFSSPKNAKRPRQEELEDFDKDGDEDECKGTTLTAAEVG...,291,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:27.492959+01
57389,Q9UGJ1,MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLC...,441,S,22067460,NaN,HTP,Homo sapiens,2011-11-14 19:43:30.010184+01

In [13]:
target_seq_len = 33
target_left_right = 16

In [14]:
def write_fasta(dataframe, file_path):
    dataframe = dataframe.drop_duplicates(subset=['sequence'])
    print("After duplicates removal")
    print(dataframe)
    data_fasta = ""
    for i, row in dataframe.iterrows():
        data_fasta += ">" + row["acc"] + "\n"
        data_fasta += row["sequence"] + "\n"
    
    with open(file_path, 'w') as f:
        f.write(data_fasta)
    return dataframe

r_S_id = list()
r_S_seq = list()
r_T_id = list()
r_T_seq = list()

for i, row in humans.iterrows():
    pos = int(row["position"])
    if pos > 33 and pos + target_left_right < len(row["sequence"]):
        extracted_seq = row["sequence"][pos - target_left_right - 1: pos + target_left_right]
        if row["code"] == "S":
            r_S_id.append(row["acc"])
            r_S_seq.append(extracted_seq)
        if row["code"] == "T":
            r_T_id.append(row["acc"])
            r_T_seq.append(extracted_seq)
        
            
S_dataframe = pd.DataFrame(zip(r_S_id, r_S_seq), columns=["acc", "sequence"])
T_dataframe = pd.DataFrame(zip(r_T_id, r_T_seq), columns=["acc", "sequence"])

print(S_dataframe)
print()
print(T_dataframe)

          acc                           sequence
0      O14746  QETSPLRDAVVIEQSSSLNEASSGLFDVFLRFM
1      O14746  VFLRFMCHHAVRIRGKSYVQCQGIPQGSILSTL
2      O14746  GVPLGLPAPGARRRGGSASRSLPLPKRPRRGAA
3      O14867  QTPQCKLRRYQGNAKASPPLQDSASQTYESMCL
4      O14867  SQKRSECPWLGIRISESPEPGQRTFTTLSSVNC
...       ...                                ...
24423  Q8NFH3  ENYISLWSIGDFGNLDSDGGFEGDHQLLCDIRH
24424  P33552  THLMSEEEWRRLGVQQSLGWVHYMIHEPEPHIL
24425  Q96SB8  ENTRPKFLSRDVDSEISDLENEVENKTAQILNL
24426  Q96SB8  RQCVEKEERFQSIAGLSTMKTNLESLKHEMAWA
24427  Q9UGJ1  HKADATQAREGPSRETSPREAPASGWAALGLSY

[24428 rows x 2 columns]

           acc                           sequence
0       O14746  RTAQTQLSRKLPGTTLTALEAAANPALPSDFKT
1       O15117  VNQDHDLKPLGPKSGPTPPTSENEQKQAFPKLT
2       O15143  RERFQNLDKKASSEGGTAAGAGLDSLHKNSVSQ
3       O15350  STMDQMSSRAASASPYTPEHAASVPTHSPYAQP
4       O15392  FLKLDRERAKNKIAKETNNKKKEFEETAKKVRR
...        ...                                ...
5657  P33981-1  KTPSSNTLDDYMSCFRTPVVKNDFPPACQLSTP
5658  P33981-1  QMQPDTTSVVKDSQVGTVNYMPPEAIKDMSSSR
5659  P33981-1  QMQPDTTSVVKDSQVGTVNYMPPEAIKDMSSSR
5660  Q9Y4B5-4  RPANRRPPSRWAPHSPTASQPQSPGDPTSLEEH
5661    P50748  HIKAHEVAQAKHKPGSTPEPIAAEVRSPSMESK

[5662 rows x 2 columns]

In [15]:
dedup_S_dataframe = write_fasta(S_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_S.fasta")  
dedup_S_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_S.tsv", sep="\t", index=None)

After duplicates removal
          acc                           sequence
0      O14746  QETSPLRDAVVIEQSSSLNEASSGLFDVFLRFM
1      O14746  VFLRFMCHHAVRIRGKSYVQCQGIPQGSILSTL
2      O14746  GVPLGLPAPGARRRGGSASRSLPLPKRPRRGAA
3      O14867  QTPQCKLRRYQGNAKASPPLQDSASQTYESMCL
4      O14867  SQKRSECPWLGIRISESPEPGQRTFTTLSSVNC
...       ...                                ...
24423  Q8NFH3  ENYISLWSIGDFGNLDSDGGFEGDHQLLCDIRH
24424  P33552  THLMSEEEWRRLGVQQSLGWVHYMIHEPEPHIL
24425  Q96SB8  ENTRPKFLSRDVDSEISDLENEVENKTAQILNL
24426  Q96SB8  RQCVEKEERFQSIAGLSTMKTNLESLKHEMAWA
24427  Q9UGJ1  HKADATQAREGPSRETSPREAPASGWAALGLSY

[16833 rows x 2 columns]

In [16]:
dedup_T_dataframe = write_fasta(T_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_T.fasta")  
dedup_T_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_T.tsv", sep="\t", index=None)

After duplicates removal
           acc                           sequence
0       O14746  RTAQTQLSRKLPGTTLTALEAAANPALPSDFKT
1       O15117  VNQDHDLKPLGPKSGPTPPTSENEQKQAFPKLT
2       O15143  RERFQNLDKKASSEGGTAAGAGLDSLHKNSVSQ
3       O15350  STMDQMSSRAASASPYTPEHAASVPTHSPYAQP
4       O15392  FLKLDRERAKNKIAKETNNKKKEFEETAKKVRR
...        ...                                ...
5653  P33981-1  LKLIDFGIANQMQPDTTSVVKDSQVGTVNYMPP
5657  P33981-1  KTPSSNTLDDYMSCFRTPVVKNDFPPACQLSTP
5658  P33981-1  QMQPDTTSVVKDSQVGTVNYMPPEAIKDMSSSR
5660  Q9Y4B5-4  RPANRRPPSRWAPHSPTASQPQSPGDPTSLEEH
5661    P50748  HIKAHEVAQAKHKPGSTPEPIAAEVRSPSMESK

[4276 rows x 2 columns]

In [17]:
# create negative dataset
S_neg_id = list()
S_neg_seq = list()

T_neg_id = list()
T_neg_seq = list()

def extract_neg_seq(original_seq, s_id, pos, s_len=33):
    r_id = list()
    r_seq = list()
    for p in pos:
        if p > s_len:
            extracted_seq = original_seq[p - target_left_right: p + target_left_right + 1]
            if len(extracted_seq) >= s_len:
                r_id.append(s_id)
                r_seq.append(extracted_seq)
    return r_id, r_seq
                        

for i, row in humans.iterrows():
    if len(row["sequence"]) > 33:

        S_pos = [pos for pos, char in enumerate(row["sequence"]) if char == "S"]
        T_pos = [pos for pos, char in enumerate(row["sequence"]) if char == "T"]
        
        if row["code"] == "S":
            # exclude POS position
            S_pos = [ item for item in S_pos if item != row["position"] - 1 ]
            ids, seqs = extract_neg_seq(row["sequence"], row["acc"], S_pos)
            S_neg_id.extend(ids)
            S_neg_seq.extend(seqs)
        if row["code"] == "T":
            # exclude POS position
            T_pos = [ item for item in T_pos if item != row["position"] - 1 ]
            ids, seqs = extract_neg_seq(row["sequence"], row["acc"], T_pos)
            T_neg_id.extend(ids)
            T_neg_seq.extend(seqs)


S_neg_dataframe = pd.DataFrame(zip(S_neg_id, S_neg_seq), columns=["acc", "sequence"])
T_neg_dataframe = pd.DataFrame(zip(T_neg_id, T_neg_seq), columns=["acc", "sequence"])

In [18]:
S_neg_dataframe

            acc                           sequence
0        O14746  CLVCVPWDARPPPAAPSFRQVSCLKELVARVLQ
1        O14746  PWDARPPPAAPSFRQVSCLKELVARVLQRLCER
2        O14746  ALLDGARGGPPEAFTTSVRSYLPNTVTDALRGS
3        O14746  DGARGGPPEAFTTSVRSYLPNTVTDALRGSGAW
4        O14746  SVRSYLPNTVTDALRGSGAWGLLLRRVGDDVLV
...         ...                                ...
2844573  Q9UGJ1  RGAAQLSILVKGFSRQSSLLFKILSSVRNHQIN
2844574  Q9UGJ1  GAAQLSILVKGFSRQSSLLFKILSSVRNHQINS
2844575  Q9UGJ1  LVKGFSRQSSLLFKILSSVRNHQINSDLAQLLL
2844576  Q9UGJ1  VKGFSRQSSLLFKILSSVRNHQINSDLAQLLLR
2844577  Q9UGJ1  SLLFKILSSVRNHQINSDLAQLLLRLDYNKYYT

[2844578 rows x 2 columns]

In [19]:
T_neg_dataframe

           acc                           sequence
0       O14746  GFALLDGARGGPPEAFTTSVRSYLPNTVTDALR
1       O14746  FALLDGARGGPPEAFTTSVRSYLPNTVTDALRG
2       O14746  GPPEAFTTSVRSYLPNTVTDALRGSGAWGLLLR
3       O14746  PEAFTTSVRSYLPNTVTDALRGSGAWGLLLRRV
4       O14746  CAYQVCGPPLYQLGAATQARPPPHASGPRRRLG
...        ...                                ...
355922  P50748  SCDPQVILKQLEEHMNTGQLAGFSHQIRSLILN
355923  P50748  ILNNIINKKEFGILAKTKYFQMLKMHAMNTNNI
355924  P50748  LAKTKYFQMLKMHAMNTNNITELVNYLANDLSL
355925  P50748  KYFQMLKMHAMNTNNITELVNYLANDLSLDEAS
355926  P50748  NYLANDLSLDEASVLITEYSKHCGKPVPPDTAP

[355927 rows x 2 columns]

In [20]:
dedup_S_neg_dataframe = write_fasta(S_neg_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_S.fasta")  
dedup_S_neg_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_S.tsv", sep="\t", index=None)

After duplicates removal
            acc                           sequence
0        O14746  CLVCVPWDARPPPAAPSFRQVSCLKELVARVLQ
1        O14746  PWDARPPPAAPSFRQVSCLKELVARVLQRLCER
2        O14746  ALLDGARGGPPEAFTTSVRSYLPNTVTDALRGS
3        O14746  DGARGGPPEAFTTSVRSYLPNTVTDALRGSGAW
4        O14746  SVRSYLPNTVTDALRGSGAWGLLLRRVGDDVLV
...         ...                                ...
2844573  Q9UGJ1  RGAAQLSILVKGFSRQSSLLFKILSSVRNHQIN
2844574  Q9UGJ1  GAAQLSILVKGFSRQSSLLFKILSSVRNHQINS
2844575  Q9UGJ1  LVKGFSRQSSLLFKILSSVRNHQINSDLAQLLL
2844576  Q9UGJ1  VKGFSRQSSLLFKILSSVRNHQINSDLAQLLLR
2844577  Q9UGJ1  SLLFKILSSVRNHQINSDLAQLLLRLDYNKYYT

[286507 rows x 2 columns]

In [21]:
dedup_T_neg_dataframe = write_fasta(T_neg_dataframe, "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_T.fasta")  
dedup_T_neg_dataframe.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_T.tsv", sep="\t", index=None)

After duplicates removal
           acc                           sequence
0       O14746  GFALLDGARGGPPEAFTTSVRSYLPNTVTDALR
1       O14746  FALLDGARGGPPEAFTTSVRSYLPNTVTDALRG
2       O14746  GPPEAFTTSVRSYLPNTVTDALRGSGAWGLLLR
3       O14746  PEAFTTSVRSYLPNTVTDALRGSGAWGLLLRRV
4       O14746  CAYQVCGPPLYQLGAATQARPPPHASGPRRRLG
...        ...                                ...
355922  P50748  SCDPQVILKQLEEHMNTGQLAGFSHQIRSLILN
355923  P50748  ILNNIINKKEFGILAKTKYFQMLKMHAMNTNNI
355924  P50748  LAKTKYFQMLKMHAMNTNNITELVNYLANDLSL
355925  P50748  KYFQMLKMHAMNTNNITELVNYLANDLSLDEAS
355926  P50748  NYLANDLSLDEASVLITEYSKHCGKPVPPDTAP

[98375 rows x 2 columns]

In [22]:
from sklearn.model_selection import train_test_split


all_neg_S = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_S.tsv", sep="\t")

all_neg_S = all_neg_S.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_neg_S.index))

test_neg_S = all_neg_S[split_size:]
train_neg_S = all_neg_S[:split_size]

train_neg_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_S.tsv", sep="\t", index=None)
test_neg_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_S.tsv", sep="\t", index=None)

In [23]:
all_pos_S = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_S.tsv", sep="\t")

all_pos_S = all_pos_S.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_pos_S.index))
test_pos_S = all_pos_S[split_size:]
train_pos_S = all_pos_S[:split_size]

train_pos_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_S.tsv", sep="\t", index=None)
test_pos_S.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_S.tsv", sep="\t", index=None)

In [24]:
all_neg_T = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_neg_T.tsv", sep="\t")

all_neg_T = all_neg_T.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_neg_T.index))

test_neg_T = all_neg_T[split_size:]
train_neg_T = all_neg_T[:split_size]

train_neg_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_T.tsv", sep="\t", index=None)
test_neg_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_T.tsv", sep="\t", index=None)

In [25]:
all_pos_T = pd.read_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/all_pos_T.tsv", sep="\t")

all_pos_T = all_pos_T.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_pos_T.index))
train_pos_T = all_pos_T[:split_size]
test_pos_T = all_pos_T[split_size:]

train_pos_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_T.tsv", sep="\t", index=None)
test_pos_T.to_csv("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_T.tsv", sep="\t", index=None)

In [26]:
def write_tsv_fasta(file_path, save_to_file, max_rows=20000):
    fasta_text = ""
    dataframe = pd.read_csv(file_path, sep="\t")
    print(dataframe)
    for i, row in dataframe.iterrows():
        fasta_text += ">" + row[0] + "\n"
        fasta_text += row[1] + "\n"
        if i > max_rows:
            break
    with open(save_to_file, "w") as f:
        f.write(fasta_text)

In [27]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_S.fasta", len(train_pos_S.index))

          acc                           sequence
0      Q9UQ35  RRSRSRASPVSRRRSRSRTPPVTRRRSRSRTPT
1      P40189  GGDGILPRQQYFKQNCSQHESSPDISHFERSKQ
2      Q92794  KKTKGLIDGLTKFFTPSPDGRKARGEVVDYSEQ
3      Q9NYF8  TIAPQNAPRDESRGRSSFYPDGGDQETAKTGKF
4      P27816  KTTTAAAVASTGPSSRSPSTLLPKKPTAIKTEG
...       ...                                ...
13461  P49792  TFKTPEKAKEKKKPEDSPSDDDVLIVYELTPTA
13462  O43765  GKEMPQDLRSPARTPPSEEDSAEAERLKTEGNE
13463  Q96BT3  EAEGSQGTAEADGPGASSGDEDASGRAASPESA
13464  Q8IU60  PFIRPLRDWLSRRFGDSSDSDNGFSSTGSTPAK
13465  Q9UBF8  PDTGLSPSKRTHQRSKSDATASISLSSNLKRTA

[13466 rows x 2 columns]

In [28]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_pos_T.fasta", len(train_pos_T.index))

         acc                           sequence
0     P19484  RIQELEMQARVHGLPTTSPSGMNMAELAQQVVK
1     Q8TCS8  DGRMRLSRKVLQSPATTVVRTLNDRSSIVMGEP
2     P19838  SVCDSGVETSFRKLSFTESLTSGASLLTLNKMP
3     Q9ULH7  KNSNSGNSALNNATPNTPRQNTSTPVRKPGPLP
4     Q6ZN55  PRATRAPVASPAALGSTATASPAAPARRRGLEC
...      ...                                ...
3415  Q9NTJ3  SDAEPEPPSGRTESPATAAETASEELDNRSLEE
3416  O15530  VLSPESKQARANSFVGTAQYVSPELLTEKSACK
3417  Q9NPI6  SDLERKASSPSPLTIGTPESQRKPSIILSKSQL
3418  O75533  ERDTPGHGSGWAETPRTDRGGDSIGETPTPGAS
3419  Q5VT52  SIDNIDGTPVRDERSGTPTQDEMMDKPTSSSVD

[3420 rows x 2 columns]

In [29]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_S.fasta", len(train_pos_S.index))

           acc                           sequence
0       O75175  SSSGGNNASSQALGPPSGPHNPPPSTSKEPSAA
1       Q9NYV4  QLEALNQSISALTEATSQQQDSETMAPEESLKE
2       Q8TCU4  VVVVEEVEEEAGRELDSDSHYGPQHLESIDDEE
3       Q9Y6N8  KISIEDVDEPPVFSRSSYLFEVHEDIEVGTIIG
4       Q5VWN6  ESSEPPFGPRNVIENKSLSDTLVSTTAPSGIVN
...        ...                                ...
229200  Q5JSL3  LKHVFASLRAFISKFPSAFFKGRVNMCAAFCYE
229201  Q96PE2  RITALLVCEELLWVGTSAGVVLTMPTSPGTVSC
229202  Q8NFC6  TDESNKETANLQERSISNDDGEEKIVTSVRRRG
229203  Q0VDD7  GTWADSLAVELDFLLDSQIQDALDASDFEAPPE
229204  Q16513  EELHHKLQELNAHIVVSDPEDITDCPRTPDTPN

[229205 rows x 2 columns]

In [30]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/train_neg_T.fasta", len(train_pos_T.index))

          acc                           sequence
0      P11532  QTALEEVLSWLLSAEDTLQAQGEISNDVEVVKD
1      Q02505  TETTSHSARSFTSSITTTETTSHNTRSFTSSIT
2      Q9NQV6  SSTSLESHMKLHSDQKTYSCIFCPESFDRLDLL
3      Q14103  GGFGEVESIELPMDNKTNKRRGFCFITFKEEEP
4      Q9BYW2  QQLLPQQLPECKVDSETNIEASKLPTSEPEADA
...       ...                                ...
78695  Q9BY89  PKDTDTLVHEAGSQYGTWTEQCQSGESLATESP
78696  Q16513  SRTSKSKSGSSRNLLKTDDLSNDVCAVLKLDNT
78697  Q8TEX9  LASAADPQIRQFAAVLTRRRLNTRWRRLAAEQR
78698  Q14789  KQKNKEFSQTLENEKNTLLSQISTKDGELKMLQ
78699  Q15058  SAENTILPEEETVVQNTSAGKDPLKVENSQVTV

[78700 rows x 2 columns]

In [31]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_S.fasta", len(test_pos_S.index))

         acc                           sequence
0     Q9NYF8  FDYSPPLHKNLDAREKSTFREESPLRIKMIASD
1     P47736  KSPTRKKSGPFGSRRSSAIGIENIQEVQEKRES
2     Q8NHM5  ELPEAPPKTRESDHSRSSSPTAGPSTEGAEGPE
3     P18887  RRLPSRRYLMAGPGSSSEEDEASHSGGSGDEAP
4     Q86W56  HNVEKLENVSQLSLDKSPTEKSTQYLNQHQTAA
...      ...                                ...
3362  P09429  FVQTCREEHKKKHPDASVNFSEFSKKCSERWKT
3363  P48634  VHPSGLVPRERSDSGGSSSEPFDRHAPAMLRER
3364  Q9BTE3  STWVKEAYVNANQARVSPSTSYTPSRHKRSYED
3365  Q9BTK6  TGRDLFSLDSEDPSPASPPLRSSGSSLFPRQRK
3366  Q01543  YDHMNGSRESPVDCSVSKCSKLVGGGESNPMNY

[3367 rows x 2 columns]

In [32]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_pos_T.fasta", len(test_pos_T.index))

        acc                           sequence
0    O43264  TVKIIPDSKINVPELPTPDEDNKLEVQKVSNTQ
1    Q15149  RFLEVQYLTGGLIEPDTPGRVPLDEALQRGTVD
2    Q96RK0  FAELPEFRPEEVLPSPTLQSLATSPRAILGSYR
3    Q9HAU0  GSHFPVGVVPPRAKSPTPESSTIASYVTLRKTK
4    P05455  AQPGSGKGKVQFQGKKTKFASDDEHDEHDENGA
..      ...                                ...
851  O94776  ATIVKDLVAQAPLKPKTPRGTKTPINRNQLSQN
852  Q9NYF8  DKESGKQKFNDSEGDDTEETEDYRQFRKSVLAD
853  P05412  QALKEEPQTVPEMPGETPPLSPIDMESQERIKA
854  Q8WWQ0  VLSDSEDEEKDADVPGTSTRKRKDHQPRRRLRN
855  Q7KZI7  GAPDRTNFPRGVSSRSTFHAGQLRQVRDQQNLP

[856 rows x 2 columns]

In [33]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_S.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_S.fasta", len(test_pos_S.index))

            acc                           sequence
0        O95071  AQLALERVLQDWNALKSMIMFGSQENKDPLSAS
1        P55201  NKEKRKDSNHHHHHNVSASTTPKLPEVVYRELE
2        O60216  QHQQRDVIDEPIIEEPSRLQESVMEASRTNIDE
3      Q9BX66-3  PQLSHHSLRAGPDLTESEKSYVQPQAQQRRVTP
4        P07949  DFQGPGAGVLLLHFNVSVLPVSLHLPSTYSLSV
...         ...                                ...
57297    Q9Y4B6  KALVGLSRSSTVRQIISKLPLFSSCQIQQLMKE
57298    O15169  LPQKLLLETAAPRVSSSRRYSEGREFRYGSWRE
57299    Q9NP78  QALEPGAATEAEGFPGSGRPPPEQASGATLQKL
57300    Q7L2J0  YQPHRPPGGGGGKRRNSCNVGGGGGGFKHPAFK
57301    Q9H1K0  THLAYALDLGSSPVPSSTAPKTPSLSSTQPTRV

[57302 rows x 2 columns]

In [34]:
write_tsv_fasta("../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_T.tsv", 
                "../dataset/phospho.elm_dataset/phosphoELM_all_latest.dump/test_neg_T.fasta", len(test_pos_T.index))

          acc                           sequence
0      Q9H1D0  LIEHGADIRAQDSLGNTVLHILILQPNKTFACQ
1      Q5T6F2  AINILLEGNSDTTSWETVGCKKKNFAKENSENK
2      P46100  HCMGLGKTLQVVSFLHTVLLCDKLDFSTALVVC
3      Q9UBK2  IEERRVIYVGKIRPDTTRTELRDRFEVFGEIEE
4      P04920  PQGPGRKPRRRPGASPTGETPTIEEGEEDEDEA
...       ...                                ...
19670  Q08AM6  RSWCHNPVTTVSLCFLTQNYRHAYDLIQKFGDL
19671  Q5T5U3  RREVHIKRMEERKASSTSPPGDSLASIPFIDEP
19672  O75962  QGDGSSQPDTISIASRTSQNTLDSDKLSGGCEL
19673  Q01167  APPLQLPRVCTFRFPSTNIKITFTALSSEKREK
19674  O60673  TQAPVKKVPVVRVFGATPAGQKTCLHLHGIFPY

[19675 rows x 2 columns]