In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
phosphosite_df = pd.read_csv("../dataset/phosphosite_org/Phosphorylation_site_dataset.csv", sep="\t")
phosphosite_df

,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,DOMAIN,SITE_+/-7_AA,LT_LIT,MS_LIT,MS_CST,CST_CAT#,Ambiguous_Site
0,0610009B22Rik,0610009B22Rik,Q8R3W2,11|11 B1.3,S119-p,1868286063,mouse,16.44,Sedlin_N,NPFYEPNsPIRSSAF,NaN,1.0,NaN,NaN,1
1,1110035H17Rik,1110035H17Rik,Q9CTA4,7|7,S10-p,7231581,mouse,24.31,NaN,RPPPGSRstVAQSPP,NaN,1.0,NaN,NaN,0
2,1110035H17Rik,1110035H17Rik,Q9CTA4,7|7,T11-p,7231583,mouse,24.31,NaN,PPPGSRstVAQSPPQ,NaN,1.0,NaN,NaN,0
3,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,28.08,NaN,______MtMDksELV,NaN,3.0,1.0,NaN,0
4,Ywhab,14-3-3 beta,Q9CQV8,2|2 H3,T2-p,15718712,mouse,28.09,NaN,______MtMDksELV,NaN,2.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378734,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S606-p,23077718,human,102.02,NaN,GLPARPksPLDPKKD,NaN,6.0,4.0,NaN,0
378735,Zzz3,ZZZ3,Q6KAQ7,3|3 H3,S613-p,23077718,mouse,102.31,NaN,GLPARPKsPLDPKKD,NaN,3.0,NaN,NaN,0
378736,ZZZ3,ZZZ3,Q8IYH5,1p31.1,Y670-p,23077724,human,102.02,Myb_DNA-binding,LEQLLIKyPPEEVEs,NaN,NaN,1.0,NaN,0
378737,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S677-p,23077721,human,102.02,Myb_DNA-binding,yPPEEVEsRRWQKIA,NaN,NaN,1.0,NaN,0
378738,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S777-p,41455930,human,102.02,NaN,NTAVEDAsDDESIPI,NaN,2.0,NaN,NaN,0

In [2]:
posphosite_humans = phosphosite_df[phosphosite_df["ORGANISM"] == "human"]
posphosite_humans

,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,DOMAIN,SITE_+/-7_AA,LT_LIT,MS_LIT,MS_CST,CST_CAT#,Ambiguous_Site
3,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,28.08,NaN,______MtMDksELV,NaN,3.0,1.0,NaN,0
5,YWHAB,14-3-3 beta,P31946,20q13.12,S6-p,15718709,human,28.08,NaN,__MtMDksELVQkAk,NaN,8.0,NaN,NaN,0
7,YWHAB,14-3-3 beta,P31946,20q13.12,Y21-p,3426383,human,28.08,14-3-3,LAEQAERyDDMAAAM,NaN,NaN,4.0,NaN,0
9,YWHAB,14-3-3 beta,P31946,20q13.12,T32-p,23077803,human,28.08,14-3-3,AAAMkAVtEQGHELs,NaN,NaN,1.0,NaN,0
10,YWHAB,14-3-3 beta,P31946,20q13.12,S39-p,27442700,human,28.08,14-3-3,tEQGHELsNEERNLL,NaN,4.0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378733,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S474-p,482028,human,102.02,NaN,PsAKESAsQHITEEE,NaN,1.0,NaN,NaN,0
378734,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S606-p,23077718,human,102.02,NaN,GLPARPksPLDPKKD,NaN,6.0,4.0,NaN,0
378736,ZZZ3,ZZZ3,Q8IYH5,1p31.1,Y670-p,23077724,human,102.02,Myb_DNA-binding,LEQLLIKyPPEEVEs,NaN,NaN,1.0,NaN,0
378737,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S677-p,23077721,human,102.02,Myb_DNA-binding,yPPEEVEsRRWQKIA,NaN,NaN,1.0,NaN,0
378738,ZZZ3,ZZZ3,Q8IYH5,1p31.1,S777-p,41455930,human,102.02,NaN,NTAVEDAsDDESIPI,NaN,2.0,NaN,NaN,0

In [5]:
posphosite_humans[posphosite_humans["ACC_ID"] == "Q6ZTW0"]

,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,DOMAIN,SITE_+/-7_AA,LT_LIT,MS_LIT,MS_CST,CST_CAT#,Ambiguous_Site
132923,TPGS1,GTRGEO22,Q6ZTW0,19p13.3,S34-p,31081198,human,31.27,NaN,RAAGAAEsEEDFLRQ,NaN,4.0,NaN,NaN,0
132924,TPGS1,GTRGEO22,Q6ZTW0,19p13.3,S251-p,56661507,human,31.27,NaN,GSRLGPDsLALALDR,NaN,1.0,NaN,NaN,0
132926,TPGS1,GTRGEO22,Q6ZTW0,19p13.3,S266-p,7820074,human,31.27,NaN,AVGGRRPsAPMTREE,NaN,4.0,NaN,NaN,0

In [23]:
fasta_file = "../dataset/phosphosite_org/Phosphosite_PTM_seq.fasta"
p_site_s = "s"
p_site_t = "t"
target_seq_len = 33
target_left_right = 16

r_S_id = list()
r_S_seq = list()
r_T_id = list()
r_T_seq = list()

for seq_record in SeqIO.parse(fasta_file, "fasta"):
        data = seq_record
        record_split = seq_record.description.split("|")
        if record_split[2] == "human":
            seq = seq_record.seq
            for index, s in enumerate(seq):
                if s == p_site_s:
                    if index > 33 and index + target_left_right < len(seq):
                        extracted_seq = seq[index - target_left_right: index + target_left_right + 1]
                        extracted_seq = extracted_seq.upper()
                        r_S_id.append(record_split[3])
                        r_S_seq.append(str(extracted_seq))
                if s == p_site_t:
                    if index > 33 and index + target_left_right < len(seq):
                        extracted_seq = seq[index - target_left_right: index + target_left_right + 1]
                        extracted_seq = extracted_seq.upper()
                        r_T_id.append(record_split[3])
                        r_T_seq.append(str(extracted_seq))
        

S_dataframe = pd.DataFrame(zip(r_S_id, r_S_seq), columns=["acc", "sequence"])

T_dataframe = pd.DataFrame(zip(r_T_id, r_T_seq), columns=["acc", "sequence"])

print(S_dataframe)
print()
print(T_dataframe)

             acc                           sequence
0       Q12797-3  DYEEVLAKAKDFRYNLSEVLQGKLGIYDADGDG
1         Q14204  AALEEKSALEQMRKFLSDPQVHTVLVERSTLKE
2         Q14204  LAFIKRTPVIDADKPVSSQLRVLTLSEDSPYET
3         Q14204  NDYNPLMKDFPLNDLLSATELDKIRQALVAIFT
4         Q14204  VNLAYENVKEVDGLDVSKEGTEAWEAAMKRYDE
...          ...                                ...
127322    Q6P3W6  DDDEDVQVEVAEKVQKSSAPREMQKAEEKEVPE
127323    Q6P3W6  DDEDVQVEVAEKVQKSSAPREMQKAEEKEVPED
127324    Q6P3W6  LSRELLDEKGPEVLQDSQDRCYSTPSGCLELTD
127325    Q6P3W6  MDEIEKYQEVEEDQDPSCPRLSRELLDEKEPEV
127326    Q6P3W6  LSRELLDEKEPEVLQDSLDRCYSTPSGYLELPD

[127327 rows x 2 columns]

          acc                           sequence
0      P51808  GFHTASSCFWDTTSDGTCTVRWENRTMNCIVNV
1      P51808  HTASSCFWDTTSDGTCTVRWENRTMNCIVNVFA
2      Q14204  GEKPKVTDFGDKVEDPTFLNQLQSGVNRWIREI
3      Q14204  DILKHGKRFHATVSFDTDTGLKQALETVNDYNP
4      Q14204  YNPLMKDFPLNDLLSATELDKIRQALVAIFTHL
...       ...                                ...
54645  O94854  TSGNTDVMQESRFSSATWPRATKSLAKGGFSEK
54646  O94854  LDPELHVLITPSLREKTESELKFEEDERWIMME
54647  O94854  EAEGEWEEEKLSDREKTFLMADEKNSLADIFEE
54648  O94854  TAVVEDGSDCLAAVLRTFGHLSLGQICCPDDPQ
54649  Q6P3W6  SHGPCDSNQPHKNIKITFEEDEVNSTLVVDRES

[54650 rows x 2 columns]
               acc                           sequence
0         Q12797-3  DYEEVLAKAKDFRYNLSEVLQGKLGIYDADGDG
1           Q14204  AALEEKSALEQMRKFLSDPQVHTVLVERSTLKE
2           Q14204  LAFIKRTPVIDADKPVSSQLRVLTLSEDSPYET
3           Q14204  NDYNPLMKDFPLNDLLSATELDKIRQALVAIFT
4           Q14204  VNLAYENVKEVDGLDVSKEGTEAWEAAMKRYDE
...            ...                                ...
127316  A0A5F9ZHR4  QSGEVLSSVXLEDRTESRQDSLELSSDFLPPIK
127317  A0A5F9ZHR4  VLSSVXLEDRTESRQDSLELSSDFLPPIKETDL
127318      Q6P3W6  LYEHLQALLTPDEPDKSQGQDLQEQLAEGCRLA
127321      Q6P3W6  LNEHLQALLTPYEPDKSQGQDLQEQLAEGCRLA
127324      Q6P3W6  LSRELLDEKGPEVLQDSQDRCYSTPSGCLELTD

[123677 rows x 2 columns]

          acc                           sequence
0      P51808  GFHTASSCFWDTTSDGTCTVRWENRTMNCIVNV
1      P51808  HTASSCFWDTTSDGTCTVRWENRTMNCIVNVFA
2      Q14204  GEKPKVTDFGDKVEDPTFLNQLQSGVNRWIREI
3      Q14204  DILKHGKRFHATVSFDTDTGLKQALETVNDYNP
4      Q14204  YNPLMKDFPLNDLLSATELDKIRQALVAIFTHL
...       ...                                ...
54644  O94854  ESSGHLDHREPQSESVTLEHVSKSIGIPEVQDF
54645  O94854  TSGNTDVMQESRFSSATWPRATKSLAKGGFSEK
54646  O94854  LDPELHVLITPSLREKTESELKFEEDERWIMME
54647  O94854  EAEGEWEEEKLSDREKTFLMADEKNSLADIFEE
54648  O94854  TAVVEDGSDCLAAVLRTFGHLSLGQICCPDDPQ

[52859 rows x 2 columns]

In [24]:
S_dataframe = S_dataframe.drop_duplicates(subset=['sequence'])

T_dataframe = T_dataframe.drop_duplicates(subset=['sequence'])

print(S_dataframe)
print()
print(T_dataframe)

               acc                           sequence
0         Q12797-3  DYEEVLAKAKDFRYNLSEVLQGKLGIYDADGDG
1           Q14204  AALEEKSALEQMRKFLSDPQVHTVLVERSTLKE
2           Q14204  LAFIKRTPVIDADKPVSSQLRVLTLSEDSPYET
3           Q14204  NDYNPLMKDFPLNDLLSATELDKIRQALVAIFT
4           Q14204  VNLAYENVKEVDGLDVSKEGTEAWEAAMKRYDE
...            ...                                ...
127316  A0A5F9ZHR4  QSGEVLSSVXLEDRTESRQDSLELSSDFLPPIK
127317  A0A5F9ZHR4  VLSSVXLEDRTESRQDSLELSSDFLPPIKETDL
127318      Q6P3W6  LYEHLQALLTPDEPDKSQGQDLQEQLAEGCRLA
127321      Q6P3W6  LNEHLQALLTPYEPDKSQGQDLQEQLAEGCRLA
127324      Q6P3W6  LSRELLDEKGPEVLQDSQDRCYSTPSGCLELTD

[123677 rows x 2 columns]

          acc                           sequence
0      P51808  GFHTASSCFWDTTSDGTCTVRWENRTMNCIVNV
1      P51808  HTASSCFWDTTSDGTCTVRWENRTMNCIVNVFA
2      Q14204  GEKPKVTDFGDKVEDPTFLNQLQSGVNRWIREI
3      Q14204  DILKHGKRFHATVSFDTDTGLKQALETVNDYNP
4      Q14204  YNPLMKDFPLNDLLSATELDKIRQALVAIFTHL
...       ...                                ...
54644  O94854  ESSGHLDHREPQSESVTLEHVSKSIGIPEVQDF
54645  O94854  TSGNTDVMQESRFSSATWPRATKSLAKGGFSEK
54646  O94854  LDPELHVLITPSLREKTESELKFEEDERWIMME
54647  O94854  EAEGEWEEEKLSDREKTFLMADEKNSLADIFEE
54648  O94854  TAVVEDGSDCLAAVLRTFGHLSLGQICCPDDPQ

[52859 rows x 2 columns]

In [25]:
def write_fasta(dataframe, file_path):
    dataframe = dataframe.drop_duplicates(subset=['sequence'])
    print("After duplicates removal")
    print(dataframe)
    data_fasta = ""
    for i, row in dataframe.iterrows():
        data_fasta += ">" + row["acc"] + "\n"
        data_fasta += row["sequence"] + "\n"
    
    with open(file_path, 'w') as f:
        f.write(data_fasta)
    return dataframe

In [26]:
dedup_S_dataframe = write_fasta(S_dataframe, "../dataset/phosphosite_org/all_pos_S.fasta")  
dedup_S_dataframe.to_csv("../dataset/phosphosite_org/all_pos_S.tsv", sep="\t", index=None)

After duplicates removal
               acc                           sequence
0         Q12797-3  DYEEVLAKAKDFRYNLSEVLQGKLGIYDADGDG
1           Q14204  AALEEKSALEQMRKFLSDPQVHTVLVERSTLKE
2           Q14204  LAFIKRTPVIDADKPVSSQLRVLTLSEDSPYET
3           Q14204  NDYNPLMKDFPLNDLLSATELDKIRQALVAIFT
4           Q14204  VNLAYENVKEVDGLDVSKEGTEAWEAAMKRYDE
...            ...                                ...
127316  A0A5F9ZHR4  QSGEVLSSVXLEDRTESRQDSLELSSDFLPPIK
127317  A0A5F9ZHR4  VLSSVXLEDRTESRQDSLELSSDFLPPIKETDL
127318      Q6P3W6  LYEHLQALLTPDEPDKSQGQDLQEQLAEGCRLA
127321      Q6P3W6  LNEHLQALLTPYEPDKSQGQDLQEQLAEGCRLA
127324      Q6P3W6  LSRELLDEKGPEVLQDSQDRCYSTPSGCLELTD

[123677 rows x 2 columns]

In [27]:
dedup_T_dataframe = write_fasta(T_dataframe, "../dataset/phosphosite_org/all_pos_T.fasta")  
dedup_T_dataframe.to_csv("../dataset/phosphosite_org/all_pos_T.tsv", sep="\t", index=None)

After duplicates removal
          acc                           sequence
0      P51808  GFHTASSCFWDTTSDGTCTVRWENRTMNCIVNV
1      P51808  HTASSCFWDTTSDGTCTVRWENRTMNCIVNVFA
2      Q14204  GEKPKVTDFGDKVEDPTFLNQLQSGVNRWIREI
3      Q14204  DILKHGKRFHATVSFDTDTGLKQALETVNDYNP
4      Q14204  YNPLMKDFPLNDLLSATELDKIRQALVAIFTHL
...       ...                                ...
54644  O94854  ESSGHLDHREPQSESVTLEHVSKSIGIPEVQDF
54645  O94854  TSGNTDVMQESRFSSATWPRATKSLAKGGFSEK
54646  O94854  LDPELHVLITPSLREKTESELKFEEDERWIMME
54647  O94854  EAEGEWEEEKLSDREKTFLMADEKNSLADIFEE
54648  O94854  TAVVEDGSDCLAAVLRTFGHLSLGQICCPDDPQ

[52859 rows x 2 columns]

In [32]:
# create negative dataset
S_neg_id = list()
S_neg_seq = list()

T_neg_id = list()
T_neg_seq = list()

def extract_neg_seq(original_seq, s_id, pos, s_len=33):
    r_id = list()
    r_seq = list()
    for p in pos:
        if p > s_len:
            extracted_seq = original_seq[p - target_left_right: p + target_left_right + 1]
            if len(extracted_seq) >= s_len:
                r_id.append(s_id)
                r_seq.append(extracted_seq)
    return r_id, r_seq
                        

for seq_record in SeqIO.parse(fasta_file, "fasta"):
        data = seq_record
        record_split = seq_record.description.split("|")
        if record_split[2] == "human":
            seq = seq_record.seq
            for index, s in enumerate(seq):
                if s == "S" and s != "s":
                    if index > 33 and index + target_left_right < len(seq):
                        extracted_seq = seq[index - target_left_right: index + target_left_right + 1]
                        extracted_seq = extracted_seq.upper()
                        S_neg_id.append(record_split[3])
                        S_neg_seq.append(str(extracted_seq))
                if s == "T" and s != "t":
                    if index > 33 and index + target_left_right < len(seq):
                        extracted_seq = seq[index - target_left_right: index + target_left_right + 1]
                        extracted_seq = extracted_seq.upper()
                        T_neg_id.append(record_split[3])
                        T_neg_seq.append(str(extracted_seq))

S_neg_dataframe = pd.DataFrame(zip(S_neg_id, S_neg_seq), columns=["acc", "sequence"])
T_neg_dataframe = pd.DataFrame(zip(T_neg_id, T_neg_seq), columns=["acc", "sequence"])

In [33]:
S_neg_dataframe

              acc                           sequence
0          P51808  LGGEDYNHNNINQWTASIVEQSLTHLVKLGKAY
1          P51808  YNHNNINQWTASIVEQSLTHLVKLGKAYKYIVT
2          P51808  LGKAYKYIVTCAVVQKSAYGFHTASSCFWDTTS
3          P51808  VTCAVVQKSAYGFHTASSCFWDTTSDGTCTVRW
4          P51808  TCAVVQKSAYGFHTASSCFWDTTSDGTCTVRWE
...           ...                                ...
1109338  P08651-5  RPVIAVHSGIARSPHPSSALHFPTTSILPQTAS
1109339  P08651-5  PVIAVHSGIARSPHPSSALHFPTTSILPQTAST
1109340  P08651-5  IARSPHPSSALHFPTTSILPQTASTYFPHTAIR
1109341  P08651-5  SSALHFPTTSILPQTASTYFPHTAIRYPPHLNP
1109342  P08651-5  RYPPHLNPQDPLKDLVSLACDPASQQPGPSWYL

[1109343 rows x 2 columns]

In [34]:
T_neg_dataframe

             acc                           sequence
0         P51808  GVLGGEDYNHNNINQWTASIVEQSLTHLVKLGK
1         P51808  HNNINQWTASIVEQSLTHLVKLGKAYKYIVTCA
2         P51808  SLTHLVKLGKAYKYIVTCAVVQKSAYGFHTASS
3         P51808  YIVTCAVVQKSAYGFHTASSCFWDTTSDGTCTV
4         P51808  QKSAYGFHTASSCFWDTTSDGTCTVRWENRTMN
...          ...                                ...
741286  P08651-5  SGIARSPHPSSALHFPTTSILPQTASTYFPHTA
741287  P08651-5  GIARSPHPSSALHFPTTSILPQTASTYFPHTAI
741288  P08651-5  HPSSALHFPTTSILPQTASTYFPHTAIRYPPHL
741289  P08651-5  SALHFPTTSILPQTASTYFPHTAIRYPPHLNPQ
741290  P08651-5  PTTSILPQTASTYFPHTAIRYPPHLNPQDPLKD

[741291 rows x 2 columns]

In [35]:
dedup_S_neg_dataframe = write_fasta(S_neg_dataframe, "../dataset/phosphosite_org/all_neg_S.fasta")  
dedup_S_neg_dataframe.to_csv("../dataset/phosphosite_org/all_neg_S.tsv", sep="\t", index=None)

After duplicates removal
              acc                           sequence
0          P51808  LGGEDYNHNNINQWTASIVEQSLTHLVKLGKAY
1          P51808  YNHNNINQWTASIVEQSLTHLVKLGKAYKYIVT
2          P51808  LGKAYKYIVTCAVVQKSAYGFHTASSCFWDTTS
3          P51808  VTCAVVQKSAYGFHTASSCFWDTTSDGTCTVRW
4          P51808  TCAVVQKSAYGFHTASSCFWDTTSDGTCTVRWE
...           ...                                ...
1109289  P15559-3  VAEQKKLEAADLVIFQSKKAVLSITTGGSGSMY
1109290  P15559-3  LEAADLVIFQSKKAVLSITTGGSGSMYSLQGIH
1109291  P15559-3  VIFQSKKAVLSITTGGSGSMYSLQGIHGDMNVI
1109292  P15559-3  FQSKKAVLSITTGGSGSMYSLQGIHGDMNVILW
1109342  P08651-5  RYPPHLNPQDPLKDLVSLACDPASQQPGPSWYL

[793706 rows x 2 columns]

In [36]:
dedup_T_neg_dataframe = write_fasta(T_neg_dataframe, "../dataset/phosphosite_org/all_neg_T.fasta")  
dedup_T_neg_dataframe.to_csv("../dataset/phosphosite_org/all_neg_T.tsv", sep="\t", index=None)

After duplicates removal
               acc                           sequence
0           P51808  GVLGGEDYNHNNINQWTASIVEQSLTHLVKLGK
1           P51808  HNNINQWTASIVEQSLTHLVKLGKAYKYIVTCA
2           P51808  SLTHLVKLGKAYKYIVTCAVVQKSAYGFHTASS
3           P51808  YIVTCAVVQKSAYGFHTASSCFWDTTSDGTCTV
4           P51808  QKSAYGFHTASSCFWDTTSDGTCTVRWENRTMN
...            ...                                ...
741200  A0A0K2S4Q6  VQVLVSSASSTENSVKTPASPTRPSQCQGSLPS
741201  A0A0K2S4Q6  SSASSTENSVKTPASPTRPSQCQGSLPSSTCFL
741202  A0A0K2S4Q6  ASPTRPSQCQGSLPSSTCFLLLPLLKVPLLLSI
741261    P15559-3  AADLVIFQSKKAVLSITTGGSGSMYSLQGIHGD
741262    P15559-3  ADLVIFQSKKAVLSITTGGSGSMYSLQGIHGDM

[526441 rows x 2 columns]

In [37]:
from sklearn.model_selection import train_test_split


all_neg_S = pd.read_csv("../dataset/phosphosite_org/all_neg_S.tsv", sep="\t")

all_neg_S = all_neg_S.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_neg_S.index))

test_neg_S = all_neg_S[split_size:]
train_neg_S = all_neg_S[:split_size]

train_neg_S.to_csv("../dataset/phosphosite_org/train_neg_S.tsv", sep="\t", index=None)
test_neg_S.to_csv("../dataset/phosphosite_org/test_neg_S.tsv", sep="\t", index=None)

In [38]:
all_pos_S = pd.read_csv("../dataset/phosphosite_org/all_pos_S.tsv", sep="\t")

all_pos_S = all_pos_S.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_pos_S.index))
test_pos_S = all_pos_S[split_size:]
train_pos_S = all_pos_S[:split_size]

train_pos_S.to_csv("../dataset/phosphosite_org/train_pos_S.tsv", sep="\t", index=None)
test_pos_S.to_csv("../dataset/phosphosite_org/test_pos_S.tsv", sep="\t", index=None)

In [39]:
all_neg_T = pd.read_csv("../dataset/phosphosite_org/all_neg_T.tsv", sep="\t")

all_neg_T = all_neg_T.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_neg_T.index))

test_neg_T = all_neg_T[split_size:]
train_neg_T = all_neg_T[:split_size]

train_neg_T.to_csv("../dataset/phosphosite_org/train_neg_T.tsv", sep="\t", index=None)
test_neg_T.to_csv("../dataset/phosphosite_org/test_neg_T.tsv", sep="\t", index=None)

In [40]:
all_pos_T = pd.read_csv("../dataset/phosphosite_org/all_pos_T.tsv", sep="\t")

all_pos_T = all_pos_T.sample(frac=1).reset_index(drop=True)

split_size = int(0.8 * len(all_pos_T.index))
train_pos_T = all_pos_T[:split_size]
test_pos_T = all_pos_T[split_size:]

train_pos_T.to_csv("../dataset/phosphosite_org/train_pos_T.tsv", sep="\t", index=None)
test_pos_T.to_csv("../dataset/phosphosite_org/test_pos_T.tsv", sep="\t", index=None)

In [41]:
def write_tsv_fasta(file_path, save_to_file, max_rows=20000):
    fasta_text = ""
    dataframe = pd.read_csv(file_path, sep="\t")
    print(dataframe)
    for i, row in dataframe.iterrows():
        fasta_text += ">" + row[0] + "\n"
        fasta_text += row[1] + "\n"
        if i > max_rows:
            break
    with open(save_to_file, "w") as f:
        f.write(fasta_text)

In [42]:
write_tsv_fasta("../dataset/phosphosite_org/train_pos_S.tsv", 
                "../dataset/phosphosite_org/train_pos_S.fasta")

          acc                           sequence
0      Q15149  CFEGLRSLVPAAELLESRVIDRELYQQLQRGER
1      Q9Y2M0  QKATRECEKSALTPGFSDNAIMLFSPDFTLRNT
2      Q5JQC9  GNKERISPRTPASKIASEMAYEAVELTAAEMRG
3      Q8IVF2  DSKFKMPKFKMPSFGVSAPGKSIEASLDVSALK
4      Q9NPA3  LADPGLDNDVGVEVGGSGGCLEERTPPVPDSGS
...       ...                                ...
98936  Q9UKF6  IIAGYCVEGTLAKHIMSEPEEITTMSGQKLPLK
98937  Q8TEK3  DIGTIMRVVELSPLKGSVSWTGKPVSYYLHTID
98938  P11171  PEPELKTDPSLDLHSLSSAETQPAQEELREDPD
98939  P12883  MNAELTAKKRKLEDECSELKRDIDDLELTLAKV
98940  Q19T08  KESEDPQKPGSSGLSESCSTANGEKDSITLISM

[98941 rows x 2 columns]

In [43]:
write_tsv_fasta("../dataset/phosphosite_org/train_pos_T.tsv", 
                "../dataset/phosphosite_org/train_pos_T.fasta")

          acc                           sequence
0      Q8NCK3  RAFRDNSTVLEHQKIHTGEKPYQCNECGKAFRK
1      Q96T88  FTYTGSGGRDLSGNKRTAEQSCDQKLTNTNRAL
2      P23921  IAKYGIRNSLLIAPMPTASTAQILGNNESIEPY
3      E9PCW1  YSHSSTRDGRRDSSDTTPLLNGSSQDRMFETMA
4      P35659  LIKKLKKPPTDEELKETIKKLLASANLEEVTMK
...       ...                                ...
42282  Q6P9G4  NKVTIPSTFAAVTIKETLNANINSTNFAPDENQ
42283  O95831  PLSKELWFSDDPNVTKTLRFKQWNGKERSIYFQ
42284  Q96GW9  RHRRLRGPSTAATRFSTGTDEHGLKIQQAAATA
42285  O75170  GDRTESCLVSGTQVLLTLLETRRVGTEGLVDSF
42286  Q8WZ42  RYQEGIFVRQGGVIRLTIPIKGKPFPICKWTKE

[42287 rows x 2 columns]

In [44]:
write_tsv_fasta("../dataset/phosphosite_org/train_neg_S.tsv", 
                "../dataset/phosphosite_org/train_neg_S.fasta", len(train_pos_S.index))

               acc                           sequence
0           Q7Z2K8  ISAGSRKTSSEKVNPESSGKTNPVSSGPGDPRS
1           O14924  PSLCASNSEPLKLKQRSLSESAATRFDVGHESI
2       A0A075B767  FDDENLIRKHTGSGILSMVNAGPNTNGSQLFIC
3           Q9UKN1  SSGSTGTTLSPARSTTSGLVGESTPSRLSPSST
4           Q14147  IPATPHLPGLFGSSTLSPHPTKGGYAVTDFLTY
...            ...                                ...
634959      Q8IZ52  TCSARLSEDLYHRCLQSVLEGLGSRTQLAMLLF
634960      Q9NY15  AEAPSCRCLPGYTQQGSECRAPNPCWPSPCSLL
634961      Q13045  VPDDIFKLDDLSVLDLSHNQLTECPRELENAKN
634962      Q02218  IIFTPKSLLRHPEARSSFDEMLPGTHFQRVIPE
634963      Q16549  RLVNAAKIWTSVPYLASYVSPVLKENKAIPQSP

[634964 rows x 2 columns]

In [45]:
write_tsv_fasta("../dataset/phosphosite_org/train_neg_T.tsv", 
                "../dataset/phosphosite_org/train_neg_T.fasta", len(train_pos_T.index))

           acc                           sequence
0       Q96KN7  LSLNILNGNTPEQVNYTEWKFSETNSFIGDGFK
1       Q6IEG0  LPVEVPLNHKRFVCDLTQADRLALYDFVVEETK
2       Q9UHI7  PIMLAIMTVWLLCYVLTLTDVLPTDPKAYGFQA
3       Q12866  ADRVYTSKSDVWAFGVTMWEIATRGMTPYPGVQ
4       Q96JQ0  SVALQDVNDNEPQFQRTFYNASLPEGTQPGTCF
...        ...                                ...
421147  O60921  DGELNLKIETELVCVTTHFKDLGNPPLASESTH
421148  O15397  FGKVLQSDEYEEVEDKTVMAMGILHTIDTILTV
421149  Q9Y6H5  KASAVIHDQHKLSTEETEISPPLVKCGSAYEPE
421150  Q04725  SCCSDGNIVVWDLQNQTMVRQFQGHTDGASCID
421151  O95251  HNFQGKEISIKEISQETAVNPVDIVSTLQALQM

[421152 rows x 2 columns]

In [46]:
write_tsv_fasta("../dataset/phosphosite_org/test_pos_S.tsv", 
                "../dataset/phosphosite_org/test_pos_S.fasta")

          acc                           sequence
0      Q96IF1  PAREQGSLDAERNQRGSFEAPRYEGSFPAGPPP
1      Q7Z6I6  EVESGWRSLPGTRASGSPEDLMPRPLPYHLPSI
2      P27708  NREELSALVAPAFAHTSQVLVDKSLKGWKEIEY
3      Q9P2D1  NLVIDTPRVRKQTRLYSAVKEDELMEFSDLESD
4      O15417  SKLDKALSLTKQDKLKSPFKFSDSAGGKSKTSG
...       ...                                ...
24731  O15499  LQALEALFVQNQYPDVSTRERLAGRIRLREERV
24732  Q9UQ35  ARRGRSRSRTPARRGRSRSRTPARRSGRSRSRT
24733  P05023  DMDELKKEVSMDDHKLSLDELHRKYGTDLSRGL
24734  Q9H6Y5  PPSRTTLKKTRGSPEPSPEAAADGPTVSPPERR
24735  Q09428  DQGKIQIQNLSVRYDSSLKPVLKHVNALIAPGQ

[24736 rows x 2 columns]

In [47]:
write_tsv_fasta("../dataset/phosphosite_org/test_pos_T.tsv", 
                "../dataset/phosphosite_org/test_pos_T.fasta")

          acc                           sequence
0      Q86UU0  HSPLVTSPSANLKSPQTPSQMVPLPSANPPGPL
1      O94822  NYVNERKSEQHLRFLSTLLDSFSSSRVFKMLLG
2      O60566  LSKENVQPLRQGRIMSTLQGALAQESACNNTLQ
3      O95625  RTLPKLYSLRIHMLKHTGVKPHACQVCGKTFIY
4      P42262  VDYDDSLVSKFIERWSTLEEKEYPGAHTTTIKY
...       ...                                ...
10567  Q92878  FRDAEEKYREMMIVMRTTELVNKDLDIYYKTLD
10568  P00533  GLEGCPTNGPKIPSIATGMVGALLLLLVVALGI
10569  Q96PY6  LHRDIKSQNIFLTKDGTVQLGDFGIARVLNSTV
10570  O14841  GTGRSGLRLEDAPKAQTGPPRVDKMTQCYFEGG
10571  Q5S007  NRMKLMIVGNTGSGKTTLLQQLMKTKKSDLGMQ

[10572 rows x 2 columns]

In [48]:
write_tsv_fasta("../dataset/phosphosite_org/test_neg_S.tsv", 
                "../dataset/phosphosite_org/test_neg_S.fasta", len(test_pos_S.index))

             acc                           sequence
0         P13611  INVYIIEVRENKTGRMSDLSVIGHPIDSESKED
1         Q9Y2K9  DHQYTIICSEKQAKVFSLPSQTCLYVHNITETS
2         P98088  STTSSPQTSTTSASTTSITSGPGTTPSPVPTTS
3         Q5VZK9  GGFSQMYACVCDWLGFSYREEVQWDVDTIYLTQ
4         Q8TC56  AASLSQDSSLSAAFAGSITTSKCAAERTEGPAV
...          ...                                ...
158737    Q8IWK6  LTCVVFVGGITQTRNASICQAVGIILHYSTLAT
158738    Q5T5X7  RLLVQLFPELFSDVDFSRGCSACGFAAKRKLES
158739  Q49A88-5  PKVHSEVQTDGNSQFASQEDSEIQRLITEMEAC
158740    Q9Y3B7  VKPDRTFEIKIGQPTVSYFLKAAAGIEKGARQT
158741    Q7L7X3  NSVGSNQSIPSMSISASSQSSSVNSLPDVSDDK

[158742 rows x 2 columns]

In [50]:
write_tsv_fasta("../dataset/phosphosite_org/test_neg_T.tsv", 
                "../dataset/phosphosite_org/test_neg_T.fasta", len(test_pos_T.index))

           acc                           sequence
0       Q6ZWK6  TWLLTAAHCFWKNKDPTQWIATFGATITPPAVK
1       Q9Y4F3  LCLIKDASEQSSSAKATPGKGSQANSGSATKNT
2       O75553  RQSSPSKSSASHASDPTTDDIFEEGFESPSKSE
3       Q96PC2  STESAAVAIWQTLQQTTGSNGSDCTLAQWPHAQ
4       Q2VY69  RWSSCLSRHQRVHNGETTFKCDGCGKRFYMNSQ
...        ...                                ...
105284  O60346  NPSLPAARGLNELQRFTKLKSLNLSNNHLGDFP
105285  P46821  DVTPLNGFSEGSKTDATDGKDYNASASTISPPS
105286  Q9UNX4  KDENSTQKRLSVKQTRTLQLDEDVLCVSYSPNQ
105287  O43374  DTIASHPKGFSGWAHLTEVDPDEEVQGEIHLRL
105288  Q9P258  EVIVSAACGRNHTLALTETGSVFAFGENKMGQL

[105289 rows x 2 columns]